{"name":"Vue.js 异常处理","slug":"Vue-js-异常处理","count":1,"postlist":[{"title":"记录下Vue中的try及Promise异常处理","uid":"2fa26015fca5f58433a95c9ef360f007","slug":"2025-07-19-05","date":"2025-07-19T14:49:21.000Z","updated":"2025-08-13T04:27:28.225Z","comments":true,"path":"api/articles/2025-07-19-05.json","keywords":null,"cover":null,"text":"try...catch 结构 .then().catch() 结构 这两种结构都是用来处理异常的，但是有些不同，这里做个文档记录下，方便日后 CV try 结构...","permalink":"/post/2025-07-19-05","photos":[],"count_time":{"symbolsCount":"1.3k","symbolsTime":"1 mins."},"categories":[{"name":"Vue.js","slug":"Vue-js","count":5,"path":"api/categories/Vue-js.json"}],"tags":[{"name":"Vue.js 异常处理","slug":"Vue-js-异常处理","count":1,"path":"api/tags/Vue-js-异常处理.json"}],"author":{"name":"Reverse","slug":"blog-author","avatar":"/images/avatar.jpg","link":"/","description":"每一次的突破，都是自我超越的见证。","socials":{"github":"https://github.com/hyhacct","twitter":"","stackoverflow":"","wechat":"","qq":"","weibo":"","zhihu":"","csdn":"","juejin":"","customs":{}}},"feature":false}]}